/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.HM.p1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohd Ashraf
 */
public class EmployeeUi extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeUi
     */
    DatabaseConnector db;
    Connection con;
    PreparedStatement select,insert,delete,update;
    ResultSet rs;
    public EmployeeUi() {
        initComponents();
        db = new DatabaseConnector();
        con = db.database_connect();
        tableread();
        table_show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtfld_name = new javax.swing.JTextField();
        txtfld_type = new javax.swing.JTextField();
        btn_search_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_return_ = new javax.swing.JButton();
        txtfld_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtfld_id_AR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfld_name_AR = new javax.swing.JTextField();
        txtfld_type_AR = new javax.swing.JTextField();
        txtfld_salary_AR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_status_AR = new javax.swing.JComboBox<>();
        btn_add_AR = new javax.swing.JButton();
        btn_remove_AR = new javax.swing.JButton();
        txtfld_un_AR = new javax.swing.JTextField();
        passfld_passwd_AR = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_Update_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_show_emp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_search_.setText("Search");
        btn_search_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Type:");

        btn_return_.setText("RETURN");
        btn_return_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_return_ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_return_)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfld_name)
                            .addComponent(txtfld_type)
                            .addComponent(txtfld_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_search_)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_return_)
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addComponent(btn_search_)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", jPanel1);

        jLabel3.setText("ID:");

        jLabel4.setText("Name:");

        jLabel5.setText("Type:");

        jLabel6.setText("Salary:");

        jLabel7.setText("Status:");

        jComboBox_status_AR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "On Leave" }));

        btn_add_AR.setText("Add");
        btn_add_AR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_ARActionPerformed(evt);
            }
        });

        btn_remove_AR.setText("Remove");
        btn_remove_AR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_ARActionPerformed(evt);
            }
        });

        jLabel8.setText("Username:");

        jLabel9.setText("Password:");

        btn_Update_.setText("Update");
        btn_Update_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfld_name_AR)
                            .addComponent(txtfld_id_AR)
                            .addComponent(txtfld_type_AR)
                            .addComponent(txtfld_salary_AR)
                            .addComponent(jComboBox_status_AR, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtfld_un_AR)
                            .addComponent(passfld_passwd_AR))
                        .addGap(510, 510, 510))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Update_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_add_AR, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btn_remove_AR)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_id_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_name_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfld_type_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_salary_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_status_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfld_un_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passfld_passwd_AR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_AR)
                    .addComponent(btn_Update_)
                    .addComponent(btn_remove_AR))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add/Remove", jPanel2);

        jTable_show_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Type", "Salary", "Username", "Password", "Status"
            }
        ));
        jTable_show_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_show_empMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_show_emp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane2)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableread()
    {
        try
        {
            select = con.prepareStatement("select * from test.EMPLOYEE");
            rs = select.executeQuery();
            
        }catch(SQLException ex){
             System.out.println(ex);
        }
          
    }
    
    private void table_show()
    {
        try{
            DefaultTableModel df = (DefaultTableModel) jTable_show_emp.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
               Vector v1 = new Vector();
               
               v1.add(rs.getInt("EMPLOYEE_ID"));
               v1.add(rs.getString("EMP_NAME"));
               v1.add(rs.getString("EMP_TYPE"));
               v1.add(rs.getInt("SALARY"));
               v1.add(rs.getString("EMP_UN"));
               v1.add(rs.getString("EMP_PASS"));
               v1.add(rs.getString("STATUS"));
               
                df.addRow(v1);
               
               //df.addRow(v1);
            }
        }catch(SQLException ex)
        {
            System.out.println(ex);
        }
    }
    
    
    private void btn_return_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_return_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuUi().setVisible(true);
    }//GEN-LAST:event_btn_return_ActionPerformed

    private void jTable_show_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_show_empMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dt= (DefaultTableModel) jTable_show_emp.getModel();
        int row = jTable_show_emp.getSelectedRow();
        String id = dt.getValueAt(row, 0).toString();
        String name = dt.getValueAt(row, 1).toString();
        String type = dt.getValueAt(row, 2).toString();
        String salary = dt.getValueAt(row, 3).toString();
        String user = dt.getValueAt(row, 4).toString();
        String pass = dt.getValueAt(row, 5).toString();
        
        
        txtfld_ID.setText(id);
        txtfld_name.setText(name);
        txtfld_type.setText(type); 
        
        txtfld_id_AR.setText(id);
        txtfld_name_AR.setText(name);
        txtfld_type_AR.setText(type);
        txtfld_salary_AR.setText(salary);
        txtfld_un_AR.setText(user);
        passfld_passwd_AR.setText(pass);
        
        
    }//GEN-LAST:event_jTable_show_empMouseClicked

    private void btn_search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_ActionPerformed
        // TODO add your handling code here:
        String id,name,type;
        int c_id=-1;
        id = txtfld_ID.getText().toString();
        if(!(id.isEmpty()))
        {
            c_id = Integer.parseInt(id);
        }
        name = txtfld_name.getText().toString();
        type = txtfld_type.getText().toString();
        if(!(name.isEmpty()) && !(type.isEmpty()) && !(c_id == -1))
        {
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMPLOYEE_ID=? AND EMP_TYPE=? AND EMP_NAME=?");
                select.setInt(1, c_id);
                select.setString(2, type);
                select.setString(3, name);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
            
        }else if(!(name.isEmpty()) && type.isEmpty() && (c_id == -1)){
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMP_NAME=?");
                select.setString(1, name);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
            
        }else if(name.isEmpty() && !(type.isEmpty()) && (c_id == -1)){
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMP_TYPE=?");
                select.setString(1, type);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
        }else if(name.isEmpty() && (type.isEmpty()) && !(c_id == -1)){
             try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMPLOYEE_ID=?");
                select.setInt(1, c_id);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
            
        }else if(!(name.isEmpty()) && !(type.isEmpty()) && (c_id == -1)){
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMP_TYPE=? AND EMP_NAME=?");
                select.setString(1, type);
                select.setString(2, name);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
        }else if(!(name.isEmpty()) && (type.isEmpty()) && !(c_id == -1)){
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMPLOYEE_ID=? AND EMP_NAME=?");
                select.setInt(1, c_id);
                select.setString(2, name);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
        }else if((name.isEmpty()) && !(type.isEmpty()) && !(c_id == -1)){
            try {
                select = con.prepareStatement("select * from test.EMPLOYEE where EMPLOYEE_ID=? AND EMP_TYPE=?");
                select.setInt(1, c_id);
                select.setString(2, type);
                rs = select.executeQuery();
                table_show();
            } catch (SQLException ex) {
               System.out.println(ex);
            }
        }else{
            tableread();
            table_show();
        }
    }//GEN-LAST:event_btn_search_ActionPerformed

    private void btn_add_ARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_ARActionPerformed
        // TODO add your handling code here:
        String name,user,pass,type,stat,salary;
        int s;
       try {
            name = txtfld_name_AR.getText().toString();
            type = txtfld_type_AR.getText().toString();
            salary = txtfld_salary_AR.getText().toString();
            user = txtfld_un_AR.getText().toString();
            pass = new String(passfld_passwd_AR.getPassword());
            stat = jComboBox_status_AR.getSelectedItem().toString();
            if(name.isEmpty() && user.isEmpty() && pass.isEmpty() && salary.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill All text filed to add new category");
            }else{
                s = Integer.parseInt(salary);
               insert = con.prepareStatement("insert into test.EMPLOYEE(EMP_NAME,EMP_UN,EMP_PASS,EMP_TYPE,STATUS,SALARY) values(?,?,?,?,?,?)");
               insert.setString(1, name);
               insert.setString(2, user);
               insert.setString(3, pass);
               insert.setString(4, type);
               insert.setString(5, stat);
               insert.setInt(6, s);
               int k = insert.executeUpdate();
               if(k == 1)
               {
                    JOptionPane.showMessageDialog(this,"data inserted!");
               }
            }
            
        }catch(SQLException ex){
            System.out.println(ex);
        }finally{
                txtfld_ID.setText("");
                txtfld_name.setText("");
                txtfld_type.setText(""); 
                txtfld_id_AR.setText("");
                txtfld_name_AR.setText("");
                txtfld_type_AR.setText("");
                txtfld_salary_AR.setText("");
                txtfld_un_AR.setText("");
                passfld_passwd_AR.setText("");
                tableread();
                table_show();
       }
    }//GEN-LAST:event_btn_add_ARActionPerformed

    private void btn_remove_ARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_ARActionPerformed
        // TODO add your handling code here:
        String name,userid;
        int id,returnValue;
        boolean k;
        name = txtfld_name_AR.getText().toString();
        userid = txtfld_id_AR.getText().toString();
        
        if(name.isEmpty() && userid.isEmpty()){
               JOptionPane.showMessageDialog(this,"Please fill All text filed to add new category");
           }else{
           try {
               returnValue = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove?", "Are you sure?", JOptionPane.YES_NO_OPTION);
    		
                if (returnValue == JOptionPane.YES_OPTION)
                {
                    id = Integer.parseInt(userid);
                    delete = con.prepareStatement("DELETE FROM TEST.EMPLOYEE WHERE EMPLOYEE_ID=? AND EMP_NAME=?");
                    delete.setInt(1, id);
                    delete.setString(2, name);
                    k = delete.execute();
                    if(k==true)
                    {
                        JOptionPane.showMessageDialog(this,"Employee Deleted");
                    }
                }
                else if (returnValue == JOptionPane.NO_OPTION)
                {
                    return;
                }
	
              
           } catch (SQLException ex) {
               Logger.getLogger(EmployeeUi.class.getName()).log(Level.SEVERE, null, ex);
           }finally{
                txtfld_ID.setText("");
                txtfld_name.setText("");
                txtfld_type.setText(""); 
                txtfld_id_AR.setText("");
                txtfld_name_AR.setText("");
                txtfld_type_AR.setText("");
                txtfld_salary_AR.setText("");
                txtfld_un_AR.setText("");
                passfld_passwd_AR.setText("");
                tableread();
                table_show();
                }
        }
    }//GEN-LAST:event_btn_remove_ARActionPerformed

    private void btn_Update_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_ActionPerformed
        // TODO add your handling code here:
        String type,stat,salary,id;
        int returnValue,k;
        id = txtfld_ID.getText().toString();
        salary = txtfld_salary_AR.getText().toString();
        stat = jComboBox_status_AR.getSelectedItem().toString();
        type = txtfld_type_AR.getText().toString();
        if(type.isEmpty() && stat.isEmpty() && salary.isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill All text filed to add new category");
        }else{
            returnValue = JOptionPane.showConfirmDialog(this, "Are you sure you want to Update?", "Are you sure?", JOptionPane.YES_NO_OPTION);
           
            if (returnValue == JOptionPane.YES_OPTION)
            {
                try {
                    update = con.prepareStatement("UPDATE test.EMPLOYEE SET SALARY=?,STATUS=?,EMP_TYPE=? where EMPLOYEE_ID=?");
                    update.setString(1, salary);
                    update.setString(2, stat);
                    update.setString(3, type);
                    update.setString(4, id);
                    k = update.executeUpdate();
                    if(k == 1){
                        JOptionPane.showMessageDialog(this,"Employee's data updated");
                    }
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(EmployeeUi.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                txtfld_ID.setText("");
                txtfld_name.setText("");
                txtfld_type.setText(""); 
                txtfld_id_AR.setText("");
                txtfld_name_AR.setText("");
                txtfld_type_AR.setText("");
                txtfld_salary_AR.setText("");
                txtfld_un_AR.setText("");
                passfld_passwd_AR.setText("");
                tableread();
                table_show();
                }
            }
            
        }
        
        
    }//GEN-LAST:event_btn_Update_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update_;
    private javax.swing.JButton btn_add_AR;
    private javax.swing.JButton btn_remove_AR;
    private javax.swing.JButton btn_return_;
    private javax.swing.JButton btn_search_;
    private javax.swing.JComboBox<String> jComboBox_status_AR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_show_emp;
    private javax.swing.JPasswordField passfld_passwd_AR;
    private javax.swing.JTextField txtfld_ID;
    private javax.swing.JTextField txtfld_id_AR;
    private javax.swing.JTextField txtfld_name;
    private javax.swing.JTextField txtfld_name_AR;
    private javax.swing.JTextField txtfld_salary_AR;
    private javax.swing.JTextField txtfld_type;
    private javax.swing.JTextField txtfld_type_AR;
    private javax.swing.JTextField txtfld_un_AR;
    // End of variables declaration//GEN-END:variables
}
